@startuml
class Alumno {
    String nombre
    String apellido1
    String apellido2
    LocalDate fechaNacimiento
    {static} String centroEducativo

    mostrar()
    String getUsername()
    getIniciales()
    {static} String getCentroEducativo()    
    {static} setCentroEducativo()
}


class Modulo {
    byte curso
    String codigo
    String nombre
    short horas
    byte periodosSemanais

    String mostrar()
    boolean hayAlumnado()
    double getSesiones()
}

Alumno "0..*" -- "0..*" Modulo : matriculado

@enduml